# Generated by Django 5.2.17 on 2026-08-22 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='trees_planted',
        ),
    ]
